import type { CopilotLanguage, CopilotResult } from "./livestock-copilot";

const labels: Record<CopilotLanguage, Record<string, string>> = {
  "en-IN": { "Your animals": "Your animals", "Milk production": "Milk production", "Health observations": "Health observations", "Recent feed records": "Recent feed records", "Breeding records": "Breeding records", "Your saved animals": "Your saved animals", "Livestock Copilot": "Livestock Copilot", records: "records", saved: "saved animals", empty: "No records found." },
  "hi-IN": { "Your animals": "आपके पशु", "Milk production": "दूध उत्पादन", "Health observations": "स्वास्थ्य रिकॉर्ड", "Recent feed records": "हाल के चारा रिकॉर्ड", "Breeding records": "प्रजनन रिकॉर्ड", "Your saved animals": "आपके सेव किए गए पशु", "Livestock Copilot": "पशुधन सहायक", records: "रिकॉर्ड", saved: "सेव किए गए पशु", empty: "कोई रिकॉर्ड नहीं मिला।" },
  "ta-IN": { "Your animals": "உங்கள் கால்நடைகள்", "Milk production": "பால் உற்பத்தி", "Health observations": "உடல்நிலை பதிவுகள்", "Recent feed records": "சமீபத்திய தீவன பதிவுகள்", "Breeding records": "இனப்பெருக்க பதிவுகள்", "Your saved animals": "சேமித்த கால்நடைகள்", "Livestock Copilot": "கால்நடை Copilot", records: "பதிவுகள்", saved: "சேமித்த கால்நடைகள்", empty: "எந்த பதிவும் கிடைக்கவில்லை." },
  "ta-Tanglish": { "Your animals": "Unga kaalnadaigal", "Milk production": "Paal urpathi", "Health observations": "Udalnilai records", "Recent feed records": "Recent theevana records", "Breeding records": "Inapperukka records", "Your saved animals": "Save pannina animals", "Livestock Copilot": "Livestock Copilot", records: "records", saved: "save pannina animals", empty: "Endha record-um kidaikkala." },
  "te-IN": { "Your animals": "మీ పశువులు", "Milk production": "పాల ఉత్పత్తి", "Health observations": "ఆరోగ్య రికార్డులు", "Recent feed records": "ఇటీవలి మేత రికార్డులు", "Breeding records": "సంతానోత్పత్తి రికార్డులు", "Your saved animals": "మీ సేవ్ చేసిన పశువులు", "Livestock Copilot": "పశుసంవర్ధక Copilot", records: "రికార్డులు", saved: "సేవ్ చేసిన పశువులు", empty: "రికార్డులు కనుగొనబడలేదు." },
  "kn-IN": { "Your animals": "ನಿಮ್ಮ ಜಾನುವಾರುಗಳು", "Milk production": "ಹಾಲಿನ ಉತ್ಪಾದನೆ", "Health observations": "ಆರೋಗ್ಯ ದಾಖಲೆಗಳು", "Recent feed records": "ಇತ್ತೀಚಿನ ಮೇವು ದಾಖಲೆಗಳು", "Breeding records": "ಸಂತಾನೋತ್ಪತ್ತಿ ದಾಖಲೆಗಳು", "Your saved animals": "ಉಳಿಸಿದ ಜಾನುವಾರುಗಳು", "Livestock Copilot": "ಜಾನುವಾರು Copilot", records: "ದಾಖಲೆಗಳು", saved: "ಉಳಿಸಿದ ಜಾನುವಾರುಗಳು", empty: "ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ." },
  "ml-IN": { "Your animals": "നിങ്ങളുടെ കന്നുകാലികൾ", "Milk production": "പാൽ ഉൽപ്പാദനം", "Health observations": "ആരോഗ്യ രേഖകൾ", "Recent feed records": "സമീപകാല തീറ്റ രേഖകൾ", "Breeding records": "പ്രജനന രേഖകൾ", "Your saved animals": "സംരക്ഷിച്ച കന്നുകാലികൾ", "Livestock Copilot": "കന്നുകാലി Copilot", records: "രേഖകൾ", saved: "സംരക്ഷിച്ച കന്നുകാലികൾ", empty: "രേഖകളൊന്നും കണ്ടെത്തിയില്ല." },
  "mr-IN": { "Your animals": "तुमची जनावरे", "Milk production": "दूध उत्पादन", "Health observations": "आरोग्य नोंदी", "Recent feed records": "अलीकडील चारा नोंदी", "Breeding records": "प्रजनन नोंदी", "Your saved animals": "सेव्ह केलेली जनावरे", "Livestock Copilot": "पशुधन Copilot", records: "नोंदी", saved: "सेव्ह केलेली जनावरे", empty: "कोणत्याही नोंदी सापडल्या नाहीत." },
  "bn-IN": { "Your animals": "আপনার পশু", "Milk production": "দুধ উৎপাদন", "Health observations": "স্বাস্থ্য রেকর্ড", "Recent feed records": "সাম্প্রতিক খাদ্য রেকর্ড", "Breeding records": "প্রজনন রেকর্ড", "Your saved animals": "সংরক্ষিত পশু", "Livestock Copilot": "পশু Copilot", records: "রেকর্ড", saved: "সংরক্ষিত পশু", empty: "কোনো রেকর্ড পাওয়া যায়নি।" },
  "gu-IN": { "Your animals": "તમારા પશુઓ", "Milk production": "દૂધ ઉત્પાદન", "Health observations": "આરોગ્ય રેકોર્ડ", "Recent feed records": "તાજેતરના ચારા રેકોર્ડ", "Breeding records": "પ્રજનન રેકોર્ડ", "Your saved animals": "સેવ કરેલા પશુઓ", "Livestock Copilot": "પશુ Copilot", records: "રેકોર્ડ", saved: "સેવ કરેલા પશુઓ", empty: "કોઈ રેકોર્ડ મળ્યો નથી." },
  "pa-IN": { "Your animals": "ਤੁਹਾਡੇ ਪਸ਼ੂ", "Milk production": "ਦੁੱਧ ਉਤਪਾਦਨ", "Health observations": "ਸਿਹਤ ਰਿਕਾਰਡ", "Recent feed records": "ਹਾਲੀਆ ਚਾਰੇ ਦੇ ਰਿਕਾਰਡ", "Breeding records": "ਪ੍ਰਜਨਨ ਰਿਕਾਰਡ", "Your saved animals": "ਸੇਵ ਕੀਤੇ ਪਸ਼ੂ", "Livestock Copilot": "ਪਸ਼ੂ Copilot", records: "ਰਿਕਾਰਡ", saved: "ਸੇਵ ਕੀਤੇ ਪਸ਼ੂ", empty: "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।" },
  "or-IN": { "Your animals": "ଆପଣଙ୍କ ପଶୁ", "Milk production": "କ୍ଷୀର ଉତ୍ପାଦନ", "Health observations": "ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ", "Recent feed records": "ସାମ୍ପ୍ରତିକ ଚାରା ରେକର୍ଡ", "Breeding records": "ପ୍ରଜନନ ରେକର୍ଡ", "Your saved animals": "ସେଭ୍ ହୋଇଥିବା ପଶୁ", "Livestock Copilot": "ପଶୁ Copilot", records: "ରେକର୍ଡ", saved: "ସେଭ୍ ହୋଇଥିବା ପଶୁ", empty: "କୌଣସି ରେକର୍ଡ ମିଳିଲା ନାହିଁ।" },
  "as-IN": { "Your animals": "আপোনাৰ পশু", "Milk production": "গাখীৰ উৎপাদন", "Health observations": "স্বাস্থ্য ৰেকৰ্ড", "Recent feed records": "শেহতীয়া খাদ্যৰ ৰেকৰ্ড", "Breeding records": "প্ৰজনন ৰেকৰ্ড", "Your saved animals": "সংৰক্ষিত পশু", "Livestock Copilot": "পশু Copilot", records: "ৰেকৰ্ড", saved: "সংৰক্ষিত পশু", empty: "কোনো ৰেকৰ্ড পোৱা নগ'ল।" },
  "ur-IN": { "Your animals": "آپ کے مویشی", "Milk production": "دودھ کی پیداوار", "Health observations": "صحت کے ریکارڈ", "Recent feed records": "حالیہ چارے کے ریکارڈ", "Breeding records": "افزائش کے ریکارڈ", "Your saved animals": "محفوظ مویشی", "Livestock Copilot": "مویشی Copilot", records: "ریکارڈ", saved: "محفوظ مویشی", empty: "کوئی ریکارڈ نہیں ملا۔" },
};

export function localizeCopilotResult(result: CopilotResult, language: CopilotLanguage): CopilotResult {
  const c = labels[language] ?? labels["en-IN"];
  const text = result.text.replace(/^(\d+) records$/, `$1 ${c.records}`).replace(/^(\d+) saved animals$/, `$1 ${c.saved}`);
  return { ...result, title: c[result.title] ?? result.title, text: text || c.empty };
}
