export type CopilotLanguage = "en-IN" | "hi-IN" | "ta-IN" | "ta-Tanglish" | "te-IN" | "kn-IN" | "ml-IN" | "mr-IN" | "bn-IN" | "gu-IN" | "pa-IN" | "or-IN" | "as-IN" | "ur-IN";

export type CopilotCopy = {
  count: string;
  countEmpty: string;
  milk: string;
  milkEmpty: string;
  health: string;
  healthEmpty: string;
  feed: string;
  feedEmpty: string;
  breeding: string;
  breedingEmpty: string;
  animals: string;
  animalsEmpty: string;
  help: string;
  signedOut: string;
  records: (count: number) => string;
};

export const copilotCopy: Record<CopilotLanguage, CopilotCopy> = {
  "en-IN": { count: "Your animals", countEmpty: "No animals are saved yet.", milk: "Milk production", milkEmpty: "I don't have milk records for that period yet.", health: "Health observations", healthEmpty: "I don't have health observations yet.", feed: "Recent feed records", feedEmpty: "I don't have feed records yet.", breeding: "Breeding records", breedingEmpty: "I don't have breeding records yet.", animals: "Your saved animals", animalsEmpty: "No animals are saved yet. Analyze an animal to add your first one.", help: "Ask me about animals, milk production, health observations, feed records, or breeding history.", signedOut: "Please sign in to use your farm Copilot.", records: (n) => `${n} record${n === 1 ? "" : "s"}` },
  "hi-IN": { count: "आपके पशु", countEmpty: "अभी कोई पशु सेव नहीं है।", milk: "दूध उत्पादन", milkEmpty: "इस अवधि के लिए दूध का रिकॉर्ड नहीं है।", health: "स्वास्थ्य अवलोकन", healthEmpty: "अभी स्वास्थ्य रिकॉर्ड नहीं है।", feed: "हाल के चारा रिकॉर्ड", feedEmpty: "अभी चारा रिकॉर्ड नहीं है।", breeding: "प्रजनन रिकॉर्ड", breedingEmpty: "अभी प्रजनन रिकॉर्ड नहीं है।", animals: "आपके सेव किए गए पशु", animalsEmpty: "अभी कोई पशु सेव नहीं है। पहला पशु जोड़ने के लिए विश्लेषण करें।", help: "पशु, दूध, स्वास्थ्य, चारा या प्रजनन के बारे में पूछें।", signedOut: "फार्म Copilot इस्तेमाल करने के लिए साइन इन करें।", records: (n) => `${n} रिकॉर्ड` },
  "ta-IN": { count: "உங்கள் கால்நடைகள்", countEmpty: "இன்னும் எந்த கால்நடையும் சேமிக்கப்படவில்லை.", milk: "பால் உற்பத்தி", milkEmpty: "இந்த காலத்திற்கான பால் பதிவு இல்லை.", health: "உடல்நிலை பதிவுகள்", healthEmpty: "இன்னும் உடல்நிலை பதிவு இல்லை.", feed: "சமீபத்திய தீவன பதிவுகள்", feedEmpty: "இன்னும் தீவன பதிவு இல்லை.", breeding: "இனப்பெருக்க பதிவுகள்", breedingEmpty: "இன்னும் இனப்பெருக்க பதிவு இல்லை.", animals: "சேமித்த கால்நடைகள்", animalsEmpty: "இன்னும் கால்நடை இல்லை. முதலில் ஒரு கால்நடையை பகுப்பாய்வு செய்யுங்கள்.", help: "கால்நடை, பால், உடல்நிலை, தீவனம் அல்லது இனப்பெருக்கம் பற்றி கேளுங்கள்.", signedOut: "Farm Copilot பயன்படுத்த உள்நுழையவும்.", records: (n) => `${n} பதிவுகள்` },
  "ta-Tanglish": { count: "Unga kaalnadaigal", countEmpty: "Innum endha kaalnadaiyum save pannala.", milk: "Paal urpathi", milkEmpty: "Indha period-ku paal record illa.", health: "Udalnilai records", healthEmpty: "Innum health record illa.", feed: "Recent theevana records", feedEmpty: "Innum theevana record illa.", breeding: "Inapperukka records", breedingEmpty: "Innum breeding record illa.", animals: "Save pannina animals", animalsEmpty: "Innum animal illa. Mudhala oru animal-ai analyze pannunga.", help: "Animal, paal, health, theevanam illa breeding pathi kelunga.", signedOut: "Farm Copilot use panna sign in pannunga.", records: (n) => `${n} records` },
  "te-IN": { count: "మీ పశువులు", countEmpty: "ఇంకా పశువులు సేవ్ చేయలేదు.", milk: "పాల ఉత్పత్తి", milkEmpty: "ఈ కాలానికి పాల రికార్డులు లేవు.", health: "ఆరోగ్య రికార్డులు", healthEmpty: "ఇంకా ఆరోగ్య రికార్డులు లేవు.", feed: "ఇటీవలి మేత రికార్డులు", feedEmpty: "ఇంకా మేత రికార్డులు లేవు.", breeding: "సంతానోత్పత్తి రికార్డులు", breedingEmpty: "ఇంకా సంతానోత్పత్తి రికార్డులు లేవు.", animals: "మీ సేవ్ చేసిన పశువులు", animalsEmpty: "ఇంకా పశువులు లేవు. ముందుగా ఒక పశువును విశ్లేషించండి.", help: "పశువులు, పాలు, ఆరోగ్యం, మేత లేదా సంతానోత్పత్తి గురించి అడగండి.", signedOut: "Farm Copilot ఉపయోగించడానికి సైన్ ఇన్ చేయండి.", records: (n) => `${n} రికార్డులు` },
  "kn-IN": { count: "ನಿಮ್ಮ ಜಾನುವಾರುಗಳು", countEmpty: "ಇನ್ನೂ ಯಾವುದೇ ಜಾನುವಾರು ಉಳಿಸಿಲ್ಲ.", milk: "ಹಾಲಿನ ಉತ್ಪಾದನೆ", milkEmpty: "ಈ ಅವಧಿಗೆ ಹಾಲಿನ ದಾಖಲೆ ಇಲ್ಲ.", health: "ಆರೋಗ್ಯ ದಾಖಲೆಗಳು", healthEmpty: "ಇನ್ನೂ ಆರೋಗ್ಯ ದಾಖಲೆಗಳಿಲ್ಲ.", feed: "ಇತ್ತೀಚಿನ ಮೇವು ದಾಖಲೆಗಳು", feedEmpty: "ಇನ್ನೂ ಮೇವು ದಾಖಲೆಗಳಿಲ್ಲ.", breeding: "ಸಂತಾನೋತ್ಪತ್ತಿ ದಾಖಲೆಗಳು", breedingEmpty: "ಇನ್ನೂ ಸಂತಾನೋತ್ಪತ್ತಿ ದಾಖಲೆಗಳಿಲ್ಲ.", animals: "ಉಳಿಸಿದ ಜಾನುವಾರುಗಳು", animalsEmpty: "ಇನ್ನೂ ಜಾನುವಾರುಗಳಿಲ್ಲ. ಮೊದಲು ಒಂದು ಜಾನುವಾರನ್ನು ವಿಶ್ಲೇಷಿಸಿ.", help: "ಜಾನುವಾರು, ಹಾಲು, ಆರೋಗ್ಯ, ಮೇವು ಅಥವಾ ಸಂತಾನೋತ್ಪತ್ತಿ ಬಗ್ಗೆ ಕೇಳಿ.", signedOut: "Farm Copilot ಬಳಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.", records: (n) => `${n} ದಾಖಲೆಗಳು` },
  "ml-IN": { count: "നിങ്ങളുടെ കന്നുകാലികൾ", countEmpty: "ഇതുവരെ കന്നുകാലികളെ സംരക്ഷിച്ചിട്ടില്ല.", milk: "പാൽ ഉൽപ്പാദനം", milkEmpty: "ഈ കാലയളവിൽ പാൽ രേഖകളില്ല.", health: "ആരോഗ്യ രേഖകൾ", healthEmpty: "ഇതുവരെ ആരോഗ്യ രേഖകളില്ല.", feed: "സമീപകാല തീറ്റ രേഖകൾ", feedEmpty: "ഇതുവരെ തീറ്റ രേഖകളില്ല.", breeding: "പ്രജനന രേഖകൾ", breedingEmpty: "ഇതുവരെ പ്രജനന രേഖകളില്ല.", animals: "സംരക്ഷിച്ച കന്നുകാലികൾ", animalsEmpty: "കന്നുകാലികളില്ല. ആദ്യം ഒരു കന്നുകാലിയെ വിശകലനം ചെയ്യുക.", help: "കന്നുകാലി, പാൽ, ആരോഗ്യം, തീറ്റ, പ്രജനനം എന്നിവയെക്കുറിച്ച് ചോദിക്കൂ.", signedOut: "Farm Copilot ഉപയോഗിക്കാൻ സൈൻ ഇൻ ചെയ്യുക.", records: (n) => `${n} രേഖകൾ` },
  "mr-IN": { count: "तुमची जनावरे", countEmpty: "अजून जनावरे सेव्ह केलेली नाहीत.", milk: "दूध उत्पादन", milkEmpty: "या कालावधीसाठी दूध नोंद नाही.", health: "आरोग्य नोंदी", healthEmpty: "अजून आरोग्य नोंदी नाहीत.", feed: "अलीकडील चारा नोंदी", feedEmpty: "अजून चारा नोंदी नाहीत.", breeding: "प्रजनन नोंदी", breedingEmpty: "अजून प्रजनन नोंदी नाहीत.", animals: "सेव्ह केलेली जनावरे", animalsEmpty: "अजून जनावरे नाहीत. प्रथम एका जनावराचे विश्लेषण करा.", help: "जनावरे, दूध, आरोग्य, चारा किंवा प्रजननाबद्दल विचारा.", signedOut: "Farm Copilot वापरण्यासाठी साइन इन करा.", records: (n) => `${n} नोंदी` },
  "bn-IN": { count: "আপনার পশু", countEmpty: "এখনও কোনো পশু সংরক্ষণ করা হয়নি।", milk: "দুধ উৎপাদন", milkEmpty: "এই সময়ের জন্য দুধের রেকর্ড নেই।", health: "স্বাস্থ্য রেকর্ড", healthEmpty: "এখনও স্বাস্থ্য রেকর্ড নেই।", feed: "সাম্প্রতিক খাদ্য রেকর্ড", feedEmpty: "এখনও খাদ্য রেকর্ড নেই।", breeding: "প্রজনন রেকর্ড", breedingEmpty: "এখনও প্রজনন রেকর্ড নেই।", animals: "সংরক্ষিত পশু", animalsEmpty: "এখনও কোনো পশু নেই। প্রথমে একটি পশু বিশ্লেষণ করুন।", help: "পশু, দুধ, স্বাস্থ্য, খাদ্য বা প্রজনন সম্পর্কে জিজ্ঞাসা করুন।", signedOut: "Farm Copilot ব্যবহার করতে সাইন ইন করুন।", records: (n) => `${n}টি রেকর্ড` },
  "gu-IN": { count: "તમારા પશુઓ", countEmpty: "હજુ કોઈ પશુ સેવ થયેલ નથી.", milk: "દૂધ ઉત્પાદન", milkEmpty: "આ સમયગાળા માટે દૂધનો રેકોર્ડ નથી.", health: "આરોગ્ય રેકોર્ડ", healthEmpty: "હજુ આરોગ્ય રેકોર્ડ નથી.", feed: "તાજેતરના ચારા રેકોર્ડ", feedEmpty: "હજુ ચારા રેકોર્ડ નથી.", breeding: "પ્રજનન રેકોર્ડ", breedingEmpty: "હજુ પ્રજનન રેકોર્ડ નથી.", animals: "સેવ કરેલા પશુઓ", animalsEmpty: "હજુ પશુ નથી. પહેલા એક પશુનું વિશ્લેષણ કરો.", help: "પશુ, દૂધ, આરોગ્ય, ચારો અથવા પ્રજનન વિશે પૂછો.", signedOut: "Farm Copilot વાપરવા સાઇન ઇન કરો.", records: (n) => `${n} રેકોર્ડ` },
  "pa-IN": { count: "ਤੁਹਾਡੇ ਪਸ਼ੂ", countEmpty: "ਅਜੇ ਕੋਈ ਪਸ਼ੂ ਸੇਵ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।", milk: "ਦੁੱਧ ਉਤਪਾਦਨ", milkEmpty: "ਇਸ ਸਮੇਂ ਲਈ ਦੁੱਧ ਦਾ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ।", health: "ਸਿਹਤ ਰਿਕਾਰਡ", healthEmpty: "ਅਜੇ ਸਿਹਤ ਰਿਕਾਰਡ ਨਹੀਂ ਹਨ।", feed: "ਹਾਲੀਆ ਚਾਰੇ ਦੇ ਰਿਕਾਰਡ", feedEmpty: "ਅਜੇ ਚਾਰੇ ਦੇ ਰਿਕਾਰਡ ਨਹੀਂ ਹਨ।", breeding: "ਪ੍ਰਜਨਨ ਰਿਕਾਰਡ", breedingEmpty: "ਅਜੇ ਪ੍ਰਜਨਨ ਰਿਕਾਰਡ ਨਹੀਂ ਹਨ।", animals: "ਸੇਵ ਕੀਤੇ ਪਸ਼ੂ", animalsEmpty: "ਅਜੇ ਪਸ਼ੂ ਨਹੀਂ ਹਨ। ਪਹਿਲਾਂ ਇੱਕ ਪਸ਼ੂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ।", help: "ਪਸ਼ੂਆਂ, ਦੁੱਧ, ਸਿਹਤ, ਚਾਰੇ ਜਾਂ ਪ੍ਰਜਨਨ ਬਾਰੇ ਪੁੱਛੋ।", signedOut: "Farm Copilot ਵਰਤਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।", records: (n) => `${n} ਰਿਕਾਰਡ` },
  "or-IN": { count: "ଆପଣଙ୍କ ପଶୁ", countEmpty: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପଶୁ ସେଭ୍ ହୋଇନାହିଁ।", milk: "କ୍ଷୀର ଉତ୍ପାଦନ", milkEmpty: "ଏହି ସମୟ ପାଇଁ କ୍ଷୀର ରେକର୍ଡ ନାହିଁ।", health: "ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ", healthEmpty: "ଏପର୍ଯ୍ୟନ୍ତ ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ ନାହିଁ।", feed: "ସାମ୍ପ୍ରତିକ ଚାରା ରେକର୍ଡ", feedEmpty: "ଏପର୍ଯ୍ୟନ୍ତ ଚାରା ରେକର୍ଡ ନାହିଁ।", breeding: "ପ୍ରଜନନ ରେକର୍ଡ", breedingEmpty: "ଏପର୍ଯ୍ୟନ୍ତ ପ୍ରଜନନ ରେକର୍ଡ ନାହିଁ।", animals: "ସେଭ୍ ହୋଇଥିବା ପଶୁ", animalsEmpty: "ଏପର୍ଯ୍ୟନ୍ତ ପଶୁ ନାହିଁ। ପ୍ରଥମେ ଗୋଟିଏ ପଶୁ ବିଶ୍ଳେଷଣ କରନ୍ତୁ।", help: "ପଶୁ, କ୍ଷୀର, ସ୍ୱାସ୍ଥ୍ୟ, ଚାରା କିମ୍ବା ପ୍ରଜନନ ବିଷୟରେ ପଚାରନ୍ତୁ।", signedOut: "Farm Copilot ବ୍ୟବହାର ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।", records: (n) => `${n} ରେକର୍ଡ` },
  "as-IN": { count: "আপোনাৰ পশু", countEmpty: "এতিয়ালৈ কোনো পশু সংৰক্ষণ কৰা হোৱা নাই।", milk: "গাখীৰ উৎপাদন", milkEmpty: "এই সময়ৰ বাবে গাখীৰৰ ৰেকৰ্ড নাই।", health: "স্বাস্থ্য ৰেকৰ্ড", healthEmpty: "এতিয়ালৈ স্বাস্থ্য ৰেকৰ্ড নাই।", feed: "শেহতীয়া খাদ্যৰ ৰেকৰ্ড", feedEmpty: "এতিয়ালৈ খাদ্যৰ ৰেকৰ্ড নাই।", breeding: "প্ৰজনন ৰেকৰ্ড", breedingEmpty: "এতিয়ালৈ প্ৰজনন ৰেকৰ্ড নাই।", animals: "সংৰক্ষিত পশু", animalsEmpty: "এতিয়ালৈ কোনো পশু নাই। প্ৰথমে এটা পশু বিশ্লেষণ কৰক।", help: "পশু, গাখীৰ, স্বাস্থ্য, খাদ্য বা প্ৰজননৰ বিষয়ে সোধক।", signedOut: "Farm Copilot ব্যৱহাৰ কৰিবলৈ ছাইন ইন কৰক।", records: (n) => `${n} ৰেকৰ্ড` },
  "ur-IN": { count: "آپ کے مویشی", countEmpty: "ابھی کوئی مویشی محفوظ نہیں کیا گیا۔", milk: "دودھ کی پیداوار", milkEmpty: "اس مدت کے لیے دودھ کا ریکارڈ موجود نہیں۔", health: "صحت کے ریکارڈ", healthEmpty: "ابھی صحت کا کوئی ریکارڈ نہیں۔", feed: "حالیہ چارے کے ریکارڈ", feedEmpty: "ابھی چارے کا کوئی ریکارڈ نہیں۔", breeding: "افزائش کے ریکارڈ", breedingEmpty: "ابھی افزائش کا کوئی ریکارڈ نہیں۔", animals: "محفوظ مویشی", animalsEmpty: "ابھی کوئی مویشی نہیں۔ پہلے ایک مویشی کا تجزیہ کریں۔", help: "مویشی، دودھ، صحت، چارہ یا افزائش کے بارے میں پوچھیں۔", signedOut: "Farm Copilot استعمال کرنے کے لیے سائن اِن کریں۔", records: (n) => `${n} ریکارڈ` },
};

export function getCopilotCopy(language: CopilotLanguage): CopilotCopy {
  return copilotCopy[language] ?? copilotCopy["en-IN"];
}
