import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Plus, Wheat } from "lucide-react";
import { toast } from "sonner";
import { DashboardShell } from "@/components/DashboardShell";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/dashboard/feed")({ head: () => ({ meta: [{ title: "Feed — Livestock Copilot" }] }), component: FeedPage });

type Animal={id:string;animal_code:string;animal_type:string;breed:string|null};
type Feed={id:string;animal_id:string;recorded_at:string;feed_type:string;quantity_kg:number;notes:string|null};

function FeedPage(){
 const [animals,setAnimals]=useState<Animal[]>([]); const [records,setRecords]=useState<Feed[]>([]); const [animalId,setAnimalId]=useState(""); const [feedType,setFeedType]=useState("Green fodder"); const [quantity,setQuantity]=useState(""); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const a=await supabase.from("animals").select("id,animal_code,animal_type,breed").order("created_at",{ascending:false});if(a.error)toast.error(a.error.message);else{setAnimals((a.data||[]) as Animal[]);if(!animalId&&a.data?.[0])setAnimalId(a.data[0].id);}const r=await supabase.from("feed_records").select("id,animal_id,recorded_at,feed_type,quantity_kg,notes").order("recorded_at",{ascending:false}).limit(30);if(r.error)toast.error(r.error.message);else setRecords((r.data||[]) as Feed[]);setLoading(false);};
 useEffect(()=>{void load();},[]);
 const save=async()=>{if(!animalId||!quantity||Number(quantity)<0)return toast.error("Select an animal and enter a valid quantity.");setSaving(true);const {error}=await supabase.from("feed_records").insert({animal_id:animalId,feed_type:feedType,quantity_kg:Number(quantity),notes:notes||null});if(error)toast.error(error.message);else{toast.success("Feed record saved");setQuantity("");setNotes("");await load();}setSaving(false);};
 return <DashboardShell title="Feed Intelligence"><div className="mx-auto max-w-6xl space-y-6"><section className="rounded-3xl bg-[#0d211b] p-7 text-white"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><Wheat className="h-6 w-6 text-[#d89a45]"/></div><div><p className="text-xs uppercase tracking-[0.18em] text-[#aabbb0]">Livestock Copilot</p><h2 className="mt-2 font-serif text-4xl">Feed intelligence</h2><p className="mt-2 text-[#b8c6be]">Keep a simple, searchable feed history for every animal.</p></div></div></section><section className="rounded-3xl border border-border bg-card p-6 shadow-soft"><h3 className="text-xl font-semibold">Record feed</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Animal<select value={animalId} onChange={e=>setAnimalId(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3">{animals.map(a=><option key={a.id} value={a.id}>{a.animal_code} · {a.breed||a.animal_type}</option>)}</select></label><label className="text-sm font-medium">Feed type<input value={feedType} onChange={e=>setFeedType(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3" placeholder="Green fodder"/></label><label className="text-sm font-medium">Quantity (kg)<input type="number" min="0" step="0.1" value={quantity} onChange={e=>setQuantity(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3" placeholder="5"/></label><label className="text-sm font-medium">Notes<input value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3" placeholder="Optional"/></label></div><button disabled={saving||!animals.length} onClick={()=>void save()} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#d89a45] px-5 py-3 font-bold disabled:opacity-50"><Plus className="h-4 w-4"/>{saving?"Saving...":"Save feed record"}</button></section><section className="rounded-3xl border border-border bg-card p-6 shadow-soft"><h3 className="text-xl font-semibold">Recent feed records</h3>{loading?<p className="mt-5 text-muted-foreground">Loading...</p>:<div className="mt-5 space-y-3">{records.length?records.map(r=>{const a=animals.find(x=>x.id===r.animal_id);return <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-muted/40 px-4 py-4"><div><p className="font-semibold">{a?.animal_code||"Animal"} · {r.feed_type}</p><p className="text-sm text-muted-foreground">{new Date(r.recorded_at).toLocaleString()}{r.notes?` · ${r.notes}`:""}</p></div><p className="font-semibold">{Number(r.quantity_kg).toFixed(1)} kg</p></div>}):<p className="text-muted-foreground">No feed records yet.</p>}</div>}</section></div></DashboardShell>;
}
