import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Camera, HeartPulse, Milk, RefreshCw, Sparkles, Wheat, CalendarDays, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/dashboard/animal/$animalId")({
  head: () => ({ meta: [{ title: "Animal Profile — Livestock Copilot" }] }),
  component: AnimalProfilePage,
});

type Animal = { id:string; farm_id:string; animal_code:string; animal_type:string; breed:string|null; confidence:number|null; image_path:string|null; image_url:string|null; analysis_explanation:string|null; features:string[]|null; created_at:string; updated_at:string };
type MilkRecord = { id:string; recorded_at:string; session:string; quantity_liters:number; notes:string|null };
type HealthRecord = { id:string; recorded_at:string; status:string; title:string; notes:string|null };

async function getImageUrl(path:string|null){ if(!path)return null; const {data,error}=await supabase.storage.from("animal-images").createSignedUrl(path,3600); return error?null:data.signedUrl; }

function AnimalProfilePage(){
 const {animalId}=Route.useParams(); const navigate=useNavigate();
 const [animal,setAnimal]=useState<Animal|null>(null); const [imageUrl,setImageUrl]=useState<string|null>(null); const [milk,setMilk]=useState<MilkRecord[]>([]); const [health,setHealth]=useState<HealthRecord[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [modal,setModal]=useState<"milk"|"health"|null>(null);
 const [milkForm,setMilkForm]=useState({quantity:"",session:"daily",notes:""}); const [healthForm,setHealthForm]=useState({title:"",status:"observation",notes:""});
 const load=async()=>{ setLoading(true); try{
   const {data,error}=await supabase.from("animals").select("id,farm_id,animal_code,animal_type,breed,confidence,image_path,image_url,analysis_explanation,features,created_at,updated_at").eq("animal_code",animalId).maybeSingle();
   if(error)throw error; if(!data){toast.error("Animal not found"); navigate({to:"/dashboard/"}); return;} setAnimal(data as Animal); setImageUrl(await getImageUrl(data.image_path));
   const [m,h]=await Promise.all([supabase.from("milk_records").select("id,recorded_at,session,quantity_liters,notes").eq("animal_id",data.id).order("recorded_at",{ascending:false}).limit(20),supabase.from("health_records").select("id,recorded_at,status,title,notes").eq("animal_id",data.id).order("recorded_at",{ascending:false}).limit(20)]);
   if(m.error)throw m.error; if(h.error)throw h.error; setMilk((m.data||[]) as MilkRecord[]); setHealth((h.data||[]) as HealthRecord[]);
 }catch(e){toast.error(e instanceof Error?e.message:"We couldn't load this animal.");}finally{setLoading(false);} };
 useEffect(()=>{void load();},[animalId]);
 const saveMilk=async()=>{if(!animal||!milkForm.quantity||Number(milkForm.quantity)<0)return toast.error("Enter a valid milk quantity."); setSaving(true); try{const {error}=await supabase.from("milk_records").insert({animal_id:animal.id,quantity_liters:Number(milkForm.quantity),session:milkForm.session,notes:milkForm.notes||null}); if(error)throw error; toast.success("Milk record saved"); setMilkForm({quantity:"",session:"daily",notes:""}); setModal(null); await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not save milk record.");}finally{setSaving(false);}};
 const saveHealth=async()=>{if(!animal||!healthForm.title.trim())return toast.error("Add a health observation title."); setSaving(true); try{const {error}=await supabase.from("health_records").insert({animal_id:animal.id,title:healthForm.title.trim(),status:healthForm.status,notes:healthForm.notes||null}); if(error)throw error; toast.success("Health record saved"); setHealthForm({title:"",status:"observation",notes:""}); setModal(null); await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not save health record.");}finally{setSaving(false);}};
 if(loading)return <main className="min-h-screen bg-[#f7f4ec] p-6 text-[#17231e]"><div className="mx-auto max-w-6xl animate-pulse space-y-6 pt-12"><div className="h-5 w-40 rounded bg-[#dfe3dc]"/><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="h-[520px] rounded-[28px] bg-[#e8e5dc]"/><div className="space-y-5"><div className="h-44 rounded-[28px] bg-[#e8e5dc]"/><div className="h-44 rounded-[28px] bg-[#e8e5dc]"/></div></div></div></main>;
 if(!animal)return null; const features=Array.isArray(animal.features)?animal.features:[]; const totalMilk=milk.reduce((s,r)=>s+Number(r.quantity_liters),0); const avgMilk=milk.length?totalMilk/milk.length:0;
 return <main className="min-h-screen bg-[#f7f4ec] text-[#17231e]">
  <header className="sticky top-0 z-20 border-b border-[#dfe3dc] bg-[#f7f4ec]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link to="/dashboard/" className="flex items-center gap-3 text-sm font-bold tracking-[0.16em]"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#0d211b] text-white">LC</span>LIVESTOCK COPILOT</Link><div className="flex items-center gap-3"><button onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-full border border-[#ccd4cd]" aria-label="Refresh"><RefreshCw className="h-4 w-4"/></button><Link to="/dashboard/" className="hidden items-center gap-2 text-sm text-[#637269] sm:flex"><ArrowLeft className="h-4 w-4"/> Farm</Link></div></div></header>
  <section className="mx-auto max-w-7xl px-5 py-8 lg:px-10 lg:py-12"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8b6b3f]">Digital animal identity</p><h1 className="mt-3 font-serif text-5xl leading-none tracking-[-0.04em] sm:text-6xl">{animal.animal_code}</h1><p className="mt-3 text-[#637269]">Saved from Livestock Copilot AI analysis.</p></div><Link to="/dashboard/analyze" className="inline-flex items-center gap-2 rounded-full bg-[#d89a45] px-5 py-3 text-sm font-bold"><Camera className="h-4 w-4"/> Analyze another</Link></div>
   <div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]">
    <div className="overflow-hidden rounded-[30px] bg-[#10251e] shadow-[0_20px_70px_rgba(13,33,27,.12)]">{imageUrl?<img src={imageUrl} alt={`${animal.breed||animal.animal_type} ${animal.animal_code}`} className="h-[520px] w-full object-cover"/>:<div className="grid h-[520px] place-items-center text-[#aabbb0]">Animal image unavailable</div>}<div className="flex items-center justify-between border-t border-white/10 px-6 py-5 text-white"><div><p className="text-xs uppercase tracking-[0.16em] text-[#8fa097]">Species</p><p className="mt-1 font-serif text-2xl">{animal.animal_type}</p></div><div className="text-right"><p className="text-xs uppercase tracking-[0.16em] text-[#8fa097]">AI confidence</p><p className="mt-1 text-2xl font-semibold">{animal.confidence==null?"—":`${animal.confidence.toFixed(1)}%`}</p></div></div></div>
    <div className="space-y-6">
     <section className="rounded-[28px] border border-[#dfe3dc] bg-white p-7 shadow-[0_16px_55px_rgba(13,33,27,.06)]"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#8b6b3f]">Predicted breed</p><h2 className="mt-3 font-serif text-4xl">{animal.breed||"Not available"}</h2></div><span className="grid h-11 w-11 place-items-center rounded-full bg-[#edf2ed]"><Sparkles className="h-5 w-5 text-[#0d211b]"/></span></div>{animal.analysis_explanation&&<p className="mt-6 leading-7 text-[#637269]">{animal.analysis_explanation}</p>}{features.length>0&&<div className="mt-6 flex flex-wrap gap-2">{features.map(f=><span key={f} className="rounded-full bg-[#f2f1eb] px-3 py-2 text-xs font-medium text-[#536159]">{f}</span>)}</div>}</section>
     <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-[24px] border border-[#dfe3dc] bg-white p-6"><Milk className="h-5 w-5 text-[#8b6b3f]"/><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#87938b]">Milk records</p><p className="mt-2 font-serif text-2xl">{milk.length?`${avgMilk.toFixed(1)} L avg`:"No records yet"}</p><p className="mt-2 text-sm leading-6 text-[#637269]">{milk.length?`${milk.length} entries · ${totalMilk.toFixed(1)} L recorded`:"Start daily production tracking."}</p><button onClick={()=>setModal("milk")} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#edf2ed] px-4 py-2 text-sm font-semibold"><Plus className="h-4 w-4"/> Record milk</button></div><div className="rounded-[24px] border border-[#dfe3dc] bg-white p-6"><HeartPulse className="h-5 w-5 text-[#8b6b3f]"/><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#87938b]">Health</p><p className="mt-2 font-serif text-2xl">{health.length?`${health.length} observations`:"No records yet"}</p><p className="mt-2 text-sm leading-6 text-[#637269]">Keep observations and care history here.</p><button onClick={()=>setModal("health")} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#edf2ed] px-4 py-2 text-sm font-semibold"><Plus className="h-4 w-4"/> Add note</button></div><div className="rounded-[24px] border border-[#dfe3dc] bg-white p-6"><Wheat className="h-5 w-5 text-[#8b6b3f]"/><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#87938b]">Feed</p><p className="mt-2 font-serif text-2xl">Not recorded</p><p className="mt-2 text-sm leading-6 text-[#637269]">Feed tracking comes next.</p></div><div className="rounded-[24px] border border-[#dfe3dc] bg-white p-6"><CalendarDays className="h-5 w-5 text-[#8b6b3f]"/><p className="mt-5 text-xs uppercase tracking-[0.16em] text-[#87938b]">First saved</p><p className="mt-2 font-serif text-2xl">{new Date(animal.created_at).toLocaleDateString()}</p><p className="mt-2 text-sm leading-6 text-[#637269]">Digital identity created.</p></div></section>
     {milk.length>0&&<section className="rounded-[28px] border border-[#dfe3dc] bg-white p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-[#8b6b3f]">Milk history</p><h3 className="mt-2 font-serif text-3xl">Recent production</h3></div><Milk className="h-6 w-6 text-[#8b6b3f]"/></div><div className="mt-6 space-y-3">{milk.slice(0,7).map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl bg-[#f5f3ed] px-4 py-3"><div><p className="font-semibold">{Number(r.quantity_liters).toFixed(1)} L · {r.session}</p><p className="text-xs text-[#758178]">{new Date(r.recorded_at).toLocaleString()}{r.notes?` · ${r.notes}`:""}</p></div></div>)}</div></section>}
     {health.length>0&&<section className="rounded-[28px] border border-[#dfe3dc] bg-white p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-[#8b6b3f]">Health history</p><h3 className="mt-2 font-serif text-3xl">Recent observations</h3></div><HeartPulse className="h-6 w-6 text-[#8b6b3f]"/></div><div className="mt-6 space-y-3">{health.slice(0,7).map(r=><div key={r.id} className="rounded-2xl bg-[#f5f3ed] px-4 py-3"><div className="flex items-center justify-between gap-4"><p className="font-semibold">{r.title}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-medium">{r.status}</span></div><p className="mt-1 text-xs text-[#758178]">{new Date(r.recorded_at).toLocaleString()}{r.notes?` · ${r.notes}`:""}</p></div>)}</div></section>}
     <section className="rounded-[28px] bg-[#0d211b] p-7 text-white sm:p-8"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-white/10"><Sparkles className="h-5 w-5 text-[#d89a45]"/></span><div><p className="text-xs uppercase tracking-[0.18em] text-[#aabbb0]">Copilot context</p><h3 className="mt-2 font-serif text-3xl">This animal now has a history.</h3><p className="mt-3 max-w-xl leading-7 text-[#b8c6be]">Milk and health records are saved with {animal.animal_code}. The Copilot can use these records as context for future farm questions.</p></div></div></section>
    </div>
   </div>
  </section>
  {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#0d211b]/55 p-5"><div className="w-full max-w-md rounded-[28px] bg-[#f7f4ec] p-7 shadow-2xl"><div className="flex items-center justify-between"><h3 className="font-serif text-3xl">{modal==="milk"?"Record milk":"Add health note"}</h3><button onClick={()=>setModal(null)} className="grid h-9 w-9 place-items-center rounded-full border border-[#ccd4cd]"><X className="h-4 w-4"/></button></div>{modal==="milk"?<div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Quantity (litres)<input value={milkForm.quantity} onChange={e=>setMilkForm({...milkForm,quantity:e.target.value})} type="number" min="0" step="0.1" className="mt-2 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3 outline-none" placeholder="8.5"/></label><label className="block text-sm font-semibold">Session<select value={milkForm.session} onChange={e=>setMilkForm({...milkForm,session:e.target.value})} className="mt-2 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3"><option value="daily">Daily</option><option value="morning">Morning</option><option value="evening">Evening</option></select></label><label className="block text-sm font-semibold">Notes<textarea value={milkForm.notes} onChange={e=>setMilkForm({...milkForm,notes:e.target.value})} className="mt-2 min-h-24 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3" placeholder="Optional note"/></label><button disabled={saving} onClick={()=>void saveMilk()} className="w-full rounded-full bg-[#d89a45] px-5 py-3 font-bold disabled:opacity-50">{saving?"Saving...":"Save milk record"}</button></div>:<div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Title<input value={healthForm.title} onChange={e=>setHealthForm({...healthForm,title:e.target.value})} className="mt-2 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3" placeholder="Routine check"/></label><label className="block text-sm font-semibold">Status<select value={healthForm.status} onChange={e=>setHealthForm({...healthForm,status:e.target.value})} className="mt-2 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3"><option value="observation">Observation</option><option value="healthy">Healthy</option><option value="attention">Needs attention</option><option value="follow_up">Follow-up</option></select></label><label className="block text-sm font-semibold">Notes<textarea value={healthForm.notes} onChange={e=>setHealthForm({...healthForm,notes:e.target.value})} className="mt-2 min-h-24 w-full rounded-2xl border border-[#ccd4cd] bg-white px-4 py-3" placeholder="What did you observe?"/></label><button disabled={saving} onClick={()=>void saveHealth()} className="w-full rounded-full bg-[#d89a45] px-5 py-3 font-bold disabled:opacity-50">{saving?"Saving...":"Save health note"}</button></div>}</div></div>}
 </main>;
}